[package]
name = "roguelike"
version = "0.1.0"
authors = ["Ian J Sikes <ianjsikes@gmail.com>"]

[dependencies]
tcod = { version = "0.12", features = ["serialization"] }
rand = "0.3.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
